export const certificationsList = [
    {
        name: "Meta Front-End Developer Specialization",
        date: "Oct 2023",
        link: "https://www.coursera.org/account/accomplishments/specialization/certificate/2DRXJCF3PZ3Y",
        organization: "Meta",
        image: "/icons/meta.png",
    },
    {
        name: "DevOps, Cloud, and Agile Foundations",
        date: "Oct 2023",
        link: "https://www.coursera.org/account/accomplishments/specialization/NL8R5SXPD235",
        organization: "IBM",
        image: "/icons/ibm.png",
    },
    {
        name: "Introduction to Containers w/ Docker, Kubernetes & OpenShift",
        date: "Nov 2023",
        link: "https://www.coursera.org/account/accomplishments/records/THLUU2D5GUEL",
        organization: "IBM",
        image: "/icons/ibm.png",
    },
    // {
    //     name: "Application Development using Microservices and Serverless",
    //     date: "Nov 2023",
    //     link: "https://www.coursera.org/account/accomplishments/records/SK5S4LWYMLB6",
    //     organization: "IBM",
    //     image: "/icons/ibm.png",
    // },
    // {
    //     name: "Introduction to Test and Behavior Driven Development",
    //     date: "Nov 2023",
    //     link: "https://www.coursera.org/account/accomplishments/records/2C4F4M8APXXG",
    //     organization: "IBM",
    //     image: "/icons/ibm.png",
    // },
    // {
    //     name: "Developing AI Applications with Python and Flask",
    //     date: "Nov 2023",
    //     link: "https://www.coursera.org/account/accomplishments/records/HNJ2T45B7CTA",
    //     organization: "IBM",
    //     image: "/icons/ibm.png",
    // },
    // {
    //     name: "Principles of UX/UI Design",
    //     date: "Sep 2023",
    //     link: "https://www.coursera.org/account/accomplishments/records/9VAG44PFFQHN",
    //     organization: "Meta",
    //     image: "/icons/meta.png",
    // },
    // {
    //     name: "Version Control",
    //     date: "Oct 2022",
    //     link: "https://www.coursera.org/account/accomplishments/verify/YY9Y4D6Z8AMR",
    //     organization: "Meta",
    //     image: "/icons/meta.png",
    // },
    // {
    //     name: "Hands-on Introduction to Linux Commands and Shell Scripting",
    //     date: "Dec 2023",
    //     link: "https://www.coursera.org/account/accomplishments/records/4GD6ZJ2W7R7A",
    //     organization: "IBM",
    //     image: "/icons/ibm.png",
    // },
    // {
    //     name: "Introduction to Databases for Back-End Development",
    //     date: "Nov 2022",
    //     link: "https://www.coursera.org/account/accomplishments/records/GCBHEHMU8VDY",
    //     organization: "Meta",
    //     image: "/icons/meta.png",
    // },
];