export const contactList = [
    {
        name: "Email",
        link: "mailto:yunji0387@gmail.com",
        username: "yunji0387@gmail.com",
        iconPath: "/icons/gmail.png",
        iconLight: "/icons/gmailLight.png",
        iconDark: "/icons/gmailDark.png",
        isAvailable: true,
    },
    {
        name: "GitHub",
        link: "https://github.com/yunji0387",
        username: "yunji0387",
        iconPath: "/icons/github.png",
        iconLight: "/icons/githubLight.png",
        iconDark: "/icons/githubDark.png",
        isAvailable: true,
    },
    {
        name: "LinkedIn",
        link: "https://www.linkedin.com/in/yunjih/",
        username: "Yun Ji How",
        iconPath: "/icons/linkedin.png",
        iconLight: "/icons/linkedinLight.png",
        iconDark: "/icons/linkedinDark.png",
        isAvailable: true,
    },
    {
        name: "X",
        link: "https://twitter.com/",
        username: "currently unavailable",
        iconPath: "/icons/twitter.png",
        iconLight: "/icons/twitterLight.png",
        iconDark: "/icons/twitterDark.png",
        isAvailable: false,
    },
];