export const projectList = [
    {
        name: "Sky Cast Weather App",
        description: "Sky Cast is a React-based web app providing current weather updates and forecasts using Google Maps APIs.",
        link: "https://sky-cast-854836ef4892.herokuapp.com/",
        github_repo: "https://github.com/yunji0387/weather-app",
        tech_stack: ['React', 'Node.js', 'Express', 'MongoDB', 'Google Maps API', 'OpenWeatherMap API', 'Heroku', 'NoSQL'],
        image: "/images/projects/skyCast.png",
    },
    {
        name: "Little Lemon Restaurant App",
        description: "The Little Lemon Restaurant's website is a modern front-end platform built with React and Material-UI, showcasing our restaurant's online presence.",
        link: "https://meta-fe-capstone.vercel.app/",
        github_repo: "https://github.com/yunji0387/meta-fe-capstone",
        tech_stack: ['React', 'MUI', 'Formik', 'Figma', 'UX/UI', 'Heroku', 'Git', 'JavaScript'],
        image: "/images/projects/littleLemon.png",
    },
    {
        name: "Text Mining: Sentiment Analysis and Recommendation System on Yelp Reviews",
        description: "This project employs text mining and sentiment analysis on Yelp reviews to construct a personalized recommendation system for users and provide businesses with valuable consumer insights.",
        link: "https://github.com/Makiato1999/COMP4710_Yelp/blob/main/ProjectReport.pdf",
        github_repo: "https://github.com/Makiato1999/COMP4710_Yelp",
        tech_stack: ['Data Mining', 'Text Mining', 'Data Analysis', 'Jupyter Notebook', 'Pandas', 'Python'],
        image: "/images/projects/yelpDataMining.png",
    },
    {
        name: "Basic Ray Tracing Technique Implementation",
        description: "Computer Graphics project centered on enhancing ray tracing with advanced techniques for accelerated rendering and image quality improvement.",
        link: "https://github.com/yunji0387/Ray_Tracing_Project/blob/main/COMP4490_Project_Report.pdf",
        github_repo: "https://github.com/yunji0387/Ray_Tracing_Project",
        tech_stack: ['Computer Graphics', 'OpenGL', 'C++', 'Git', 'Ray Tracing'],
        image: "/images/projects/rayTracing.png",
    },
    {
        name: "2D Platformer Game in Godot",
        description: "A 2D platformer game developed in Godot, a free and open-source game engine.",
        link: "https://github.com/yunji0387/my-first-godot-game",
        github_repo: "https://github.com/yunji0387/my-first-godot-game",
        tech_stack: ['Godot', 'GDScript', 'Git', 'Game Development', '2D Game'],
        image: "/images/projects/godotGame.png",
    },
    {
        name: "Hydrological Data Analysis",
        description: "This study presents an analysis and forecasting of Cedar Lake's hydrological patterns using data from the Oleson Point station, supplied by Manitoba Hydro.",
        link: "https://github.com/yunji0387/hydrological_analysis",
        github_repo: "https://github.com/yunji0387/hydrological_analysis",
        tech_stack: ['Data Analysis', 'Jupyter Notebook', 'Pandas', 'Python'],
        image: "/images/projects/hydrologicalAnalysis.png",
    },
    {
        name: "React Portfolio Website",
        description: "This website is a React-based portfolio web app.",
        link: "https://yunji0387.github.io/my-portfolio/",
        github_repo: "https://github.com/yunji0387/my-portfolio",
        tech_stack: ['React', 'Heroku', 'Git', 'JavaScript', 'HTML', 'CSS'],
        image: "/images/projects/reactPortfolio.png",
    },
    {
        name: "React Mini Games Website",
        description: "This website is a React-based mini games web app.",
        link:"https://yunji0387.github.io/react-game-web/",
        github_repo: "https://github.com/yunji0387/react-game-web",
        tech_stack: ['React', 'Git', 'JavaScript', 'HTML', 'CSS'],
        image: "/images/projects/miniGameWeb.png",
    },
    {
        name: "Your Daily Web",
        description: "a website that provides basic information on stocks, cryptocurrencies, weather, and more.",
        link: "http://dailyweb-51c4ca40411a.herokuapp.com/home",
        github_repo: "https://github.com/yunji0387/DailyWebBlog-v1",
        tech_stack: ['Node.js', 'EJS', 'Heroku', 'RESTful API','JavaScript', 'HTML', 'CSS', 'JQuery', 'AJAX'],
        image: "/images/projects/yourDailyWeb.png",
    },
];